[font]
size = 10.5

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Paste"
key = "Y"
mods = "Control"

[scrolling]
history = 30000

[terminal]

[terminal.shell]
program = "/usr/bin/zsh"
